language: node_js
node_js:
  - "0.11"

before_script:
  - npm install

script:
  - npm run deploy
  - npm install zab/zab-cli -g
  - zab build
  - zab deploy --key $zab_api_key

after_failure:
  - cat /home/travis/build/tannerlinsley/valleydesignbuild/npm-debug.log
